baseurl = "https://ea4rct.org/"
title = "RadioClub EIT"
theme = "whiteclub"
languageCode = "es"
paginatePath = "blog"

# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright 2018 RadioClub EIT"

# Build future content [IMPORTANT]
buildfuture = true

[params]
  # whether to use CDN or local file for fontawesome
  #useCDN = false
  # whether to include external sharing scripts and icons for twitter, facebook and co.
  #showShareIcons = false
  # Date format
  dateFormat = "2 January, 2006"

# This is displayer in About page.
[params.author]
  name = "RadioClub EIT"
  # Gravatar or Abatar image
  gravatar = "Gravatar email or MD5 Hash"
  #avatar = "/path/to/avatar"

  twitter = "Twitter username"
  github = "Github username"
  gitlab = "Gitlab username"
  email = "Your email"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# Header Menu
[[menu.main]]
  name = "Próximas actividades"
  identifier = "activities"
  url = "/activities/"
  weight = 1
[[menu.main]]
  name = "Blog"
  identifier = "blog"
  url = "/blog/"
  weight = 1
[[menu.main]]
  name = "Categories"
  identifier = "categories"
  url = "/categories/"
  weight = 1
[[menu.main]]
  name = "Tags"
  identifier = "tags"
  url = "/tags/"
  weight = 2
[[menu.main]]
  name = "Archives"
  identifier = "archives"
  url = "/archives/"
  weight = 3
[[menu.main]]
  name = "Team"
  identifier = "team"
  url = "/team/"
  weight = 3
[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about/"
  weight = 4

# Footer Menu
[[menu.footer]]
  name = "About"
  weight = 1
  identifier = "about"
  url = "/about/"
