baseurl = "https://radio.clubs.etsit.upm.es"
title = "RadioClub EIT"
theme = "whiteclub"
languageCode = "es"
paginatePath = "blog"

# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright 2018 RadioClub EIT"

# Build future content [IMPORTANT]
buildfuture = true

[params]
  # whether to use CDN or local file for fontawesome
  #useCDN = false
  # whether to include external sharing scripts and icons for twitter, facebook and co.
  #showShareIcons = false
  # Date format
  dateFormat = "2 January, 2006"
  description = "EA4RCT"
  avatar = "/logo.png"

# This is displayer in About page.
[params.about]
  twitter = "ea4rct"
  #github = "Github username"
  gitea = "http://git.radio.clubs.etsit.upm.es"
  email = "info@ea4rct.org"

  localizacion =  "Avenida Complutense Nº30 Local 101.3-L"
  codigopostal =  "28040, Madrid"
  metro = "Metro: Ciudad Universitaria, Vicente Aleixandre"
  cif = "G28939353"
  # telefono =
  #horario = "De lunes a viernes de 9 a 21"


[taxonomies]
  category = "categorias"
  tag = "tags"
  series = "series"

# Header Menu
[[menu.main]]
  name = "Próximas actividades"
  identifier = "activities"
  url = "/activities/"
  weight = 1
[[menu.main]]
  name = "Blog"
  identifier = "blog"
  url = "/blog/"
  weight = 2
[[menu.main]]
  name = "Categorias"
  identifier = "categorias"
  url = "/categorias/"
  weight = 3
[[menu.main]]
  name = "Tags"
  identifier = "tags"
  url = "/tags/"
  weight = 4
[[menu.main]]
  name = "Archivo"
  identifier = "archives"
  url = "/archives/"
  weight = 5
[[menu.main]]
  name = "Quiénes somos"
  identifier = "team"
  url = "/team/"
  weight = 6
[[menu.main]]
  name = "Contacto"
  identifier = "about"
  url = "/about/"
  weight = 7

# Footer Menu
[[menu.footer]]
  name = "About"
  weight = 1
  identifier = "about"
  url = "/about/"
