name: deploy-hugo

on:
  push:
    branches:
      - master  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.83.1'
          # extended: true

      - name: Build
        run: hugo --minify
      
      - name: Deploy
        run: |
          - mkdir -p ~/.ssh
          - echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          - chmod 600 ~/.ssh/id_rsa && chmod 700 ~/.ssh
          - eval "$(ssh-agent -s)"
          - ssh-add ~/.ssh/id_rsa
          - ssh-keyscan -p ${{ secrets.PORT }} -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          - scp -r -P ${{ secrets.PORT }} public/* ${{ secrets.USER }}@${{ secrets.HOST }}:/home/hugo/ea4rct-web
